### ISSUE TITLE
OOM crash of generate_data.py

### ISSUE THREAD

**Issue by ondrzel** [gwastro/ml-mock-data-challenge-1#12]
Running `generate_data.py --duration 2592000` on the ARA cluster, even with 128 GB of memory allocated the script crashes due to insufficient memory once 743300 seconds of data have been saved in the background output file, irrespective of the `-d` option. Adding some garbage collection seems to be helpful, probably a memory leak.

**Comment by MarlinSchaefer** [comment]
Fixed by #13.
